package andrews.ubs.init;

import java.util.ArrayList;
import java.util.List;

import andrews.ubs.objects.blocks.BlockAvocadoButton;
import andrews.ubs.objects.blocks.BlockAvocadoDoor;
import andrews.ubs.objects.blocks.BlockAvocadoFence;
import andrews.ubs.objects.blocks.BlockAvocadoFenceGate;
import andrews.ubs.objects.blocks.BlockAvocadoLadder;
import andrews.ubs.objects.blocks.BlockAvocadoPressurePlate;
import andrews.ubs.objects.blocks.BlockAvocadoSlabDouble;
import andrews.ubs.objects.blocks.BlockAvocadoSlabHalf;
import andrews.ubs.objects.blocks.BlockAvocadoStairs;
import andrews.ubs.objects.blocks.BlockAvocadoTrapdoor;
import andrews.ubs.objects.blocks.BlockCampFire;
import andrews.ubs.objects.blocks.BlockCandel;
import andrews.ubs.objects.blocks.BlockChakraInfusedBerryBush;
import andrews.ubs.objects.blocks.BlockChakraInfusedBerryBushWB;
import andrews.ubs.objects.blocks.BlockChakraInfusedBush;
import andrews.ubs.objects.blocks.BlockChakraInfusedButton;
import andrews.ubs.objects.blocks.BlockChakraInfusedDoor;
import andrews.ubs.objects.blocks.BlockChakraInfusedFence;
import andrews.ubs.objects.blocks.BlockChakraInfusedFenceGate;
import andrews.ubs.objects.blocks.BlockChakraInfusedFlower;
import andrews.ubs.objects.blocks.BlockChakraInfusedGrass;
import andrews.ubs.objects.blocks.BlockChakraInfusedLadder;
import andrews.ubs.objects.blocks.BlockChakraInfusedMushroom;
import andrews.ubs.objects.blocks.BlockChakraInfusedPressurePlate;
import andrews.ubs.objects.blocks.BlockChakraInfusedSlabDouble;
import andrews.ubs.objects.blocks.BlockChakraInfusedSlabHalf;
import andrews.ubs.objects.blocks.BlockChakraInfusedStairs;
import andrews.ubs.objects.blocks.BlockChakraInfusedTallBush;
import andrews.ubs.objects.blocks.BlockChakraInfusedTrapdoor;
import andrews.ubs.objects.blocks.BlockChakraOre;
import andrews.ubs.objects.blocks.BlockCookingPot;
import andrews.ubs.objects.blocks.BlockEndChakraOre;
import andrews.ubs.objects.blocks.BlockFallingTrapCobblestone;
import andrews.ubs.objects.blocks.BlockFallingTrapCobblestoneSmart;
import andrews.ubs.objects.blocks.BlockFallingTrapFrame;
import andrews.ubs.objects.blocks.BlockFallingTrapFrameSmart;
import andrews.ubs.objects.blocks.BlockFallingTrapGrass;
import andrews.ubs.objects.blocks.BlockFallingTrapGrassSmart;
import andrews.ubs.objects.blocks.BlockFallingTrapNether;
import andrews.ubs.objects.blocks.BlockFallingTrapNetherSmart;
import andrews.ubs.objects.blocks.BlockFallingTrapSand;
import andrews.ubs.objects.blocks.BlockFallingTrapSandSmart;
import andrews.ubs.objects.blocks.BlockFallingTrapStone;
import andrews.ubs.objects.blocks.BlockFallingTrapStoneSmart;
import andrews.ubs.objects.blocks.BlockGrill;
import andrews.ubs.objects.blocks.BlockNetherChakraOre;
import andrews.ubs.objects.blocks.BlockNetherSalt;
import andrews.ubs.objects.blocks.BlockSalad;
import andrews.ubs.objects.blocks.BlockSpikes;
import andrews.ubs.objects.blocks.BlockStonePath;
import andrews.ubs.objects.blocks.BlockStoneSalt;
import andrews.ubs.objects.blocks.BlockTomato;
import andrews.ubs.objects.blocks.BlockUBSPlanks;
import andrews.ubs.objects.blocks.BlockWildSalad;
import andrews.ubs.objects.blocks.BlockWildTomato;
import net.minecraft.block.Block;
import net.minecraft.block.BlockSlab;

public class BlockInit
{
	public static final List<Block> BLOCKS = new ArrayList<Block>();
	
	public static final Block AVOCADO_BUTTON = new BlockAvocadoButton("avocado_button");
	public static final Block AVOCADO_DOOR = new BlockAvocadoDoor("avocado_door");
	public static final Block AVOCADO_FENCE = new BlockAvocadoFence("avocado_fence");
	public static final Block AVOCADO_FENCE_GATE = new BlockAvocadoFenceGate("avocado_fence_gate");
	public static final Block AVOCADO_LADDER = new BlockAvocadoLadder("avocado_ladder");
	public static final Block AVOCADO_PRESSURE_PLATE = new BlockAvocadoPressurePlate("avocado_pressure_plate");
	public static final Block AVOCADO_STAIRS = new BlockAvocadoStairs("avocado_stairs");
	public static final Block AVOCADO_TRAPDOOR = new BlockAvocadoTrapdoor("avocado_trapdoor");
	public static final Block CAMP_FIRE = new BlockCampFire("camp_fire");
	public static final Block CANDEL = new BlockCandel("candel");
	public static final Block CHAKRA_INFUSED_BERRY_BUSH = new BlockChakraInfusedBerryBush("chakra_infused_berry_bush");
	public static final Block CHAKRA_INFUSED_BERRY_BUSH_WB = new BlockChakraInfusedBerryBushWB("chakra_infused_berry_bushwb");
	public static final Block CHAKRA_INFUSED_BUSH = new BlockChakraInfusedBush("chakra_infused_bush");
	public static final Block CHAKRA_INFUSED_BUTTON = new BlockChakraInfusedButton("chakra_infused_button");
	public static final Block CHAKRA_INFUSED_FENCE = new BlockChakraInfusedFence("chakra_infused_fence");
	public static final Block CHAKRA_INFUSED_FENCE_GATE = new BlockChakraInfusedFenceGate("chakra_infused_fence_gate");
	public static final Block CHAKRA_INFUSED_FLOWER = new BlockChakraInfusedFlower("chakra_infused_flower");
	public static final Block CHAKRA_INFUSED_GRASS = new BlockChakraInfusedGrass("chakra_infused_grass");
	public static final Block CHAKRA_INFUSED_DOOR = new BlockChakraInfusedDoor("chakra_infused_door");
	public static final Block CHAKRA_INFUSED_LADDER = new BlockChakraInfusedLadder("chakra_infused_ladder");
	public static final Block CHAKRA_INFUSED_MUSHROOM = new BlockChakraInfusedMushroom("chakra_infused_mushroom");
	public static final Block CHAKRA_INFUSED_PRESSURE_PLATE = new BlockChakraInfusedPressurePlate("chakra_infused_pressure_plate");
	public static final Block CHAKRA_INFUSED_STAIRS = new BlockChakraInfusedStairs("chakra_infused_stairs");
	public static final Block CHAKRA_INFUSED_TALL_BUSH = new BlockChakraInfusedTallBush("chakra_infused_tall_bush");
	public static final Block CHAKRA_INFUSED_TRAPDOOR = new BlockChakraInfusedTrapdoor("chakra_infused_trapdoor");
	public static final Block SALAD = new BlockSalad("salad");
	public static final Block TOMATO = new BlockTomato("tomato");
	public static final BlockSlab AVOCADO_SLAB_DOUBLE = new BlockAvocadoSlabDouble("avocado_slab_double");
	public static final BlockSlab AVOCADO_SLAB_HALF = new BlockAvocadoSlabHalf("avocado_slab_half");
	public static final BlockSlab CHAKRA_INFUSED_SLAB_DOUBLE = new BlockChakraInfusedSlabDouble("chakra_infused_slab_double");
	public static final BlockSlab CHAKRA_INFUSED_SLAB_HALF = new BlockChakraInfusedSlabHalf("chakra_infused_slab_half");
	public static final Block GRILL = new BlockGrill("grill");
	public static final Block WILD_SALAD = new BlockWildSalad("wild_salad");
	public static final Block STONE_SALT = new BlockStoneSalt("stone_salt");
	public static final Block NETHER_SALT = new BlockNetherSalt("nether_salt");
	public static final Block STONE_PATH = new BlockStonePath("stone_path");
	public static final Block WILD_TOMATO = new BlockWildTomato("wild_tomato");
	public static final Block CHAKRA_ORE = new BlockChakraOre("chakra_ore");
	public static final Block NETHER_CHAKRA_ORE = new BlockNetherChakraOre("nether_chakra_ore");
	public static final Block END_CHAKRA_ORE = new BlockEndChakraOre("end_chakra_ore");
	public static final Block COOKING_POT = new BlockCookingPot("cooking_pot");
	public static final Block SPIKES = new BlockSpikes("spikes");
	public static final Block FALLING_TRAP_FRAME = new BlockFallingTrapFrame("falling_trap_frame");
	public static final Block FALLING_TRAP_GRASS = new BlockFallingTrapGrass("falling_trap_grass");
	public static final Block FALLING_TRAP_STONE = new BlockFallingTrapStone("falling_trap_stone");
	public static final Block FALLING_TRAP_COBBLESTONE = new BlockFallingTrapCobblestone("falling_trap_cobblestone");
	public static final Block FALLING_TRAP_NETHER = new BlockFallingTrapNether("falling_trap_nether");
	public static final Block FALLING_TRAP_SAND = new BlockFallingTrapSand("falling_trap_sand");
	public static final Block FALLING_TRAP_FRAME_SMART = new BlockFallingTrapFrameSmart("falling_trap_frame_smart");
	public static final Block FALLING_TRAP_GRASS_SMART = new BlockFallingTrapGrassSmart("falling_trap_grass_smart");
	public static final Block FALLING_TRAP_STONE_SMART = new BlockFallingTrapStoneSmart("falling_trap_stone_smart");
	public static final Block FALLING_TRAP_COBBLESTONE_SMART = new BlockFallingTrapCobblestoneSmart("falling_trap_cobblestone_smart");
	public static final Block FALLING_TRAP_NETHER_SMART = new BlockFallingTrapNetherSmart("falling_trap_nether_smart");
	public static final Block FALLING_TRAP_SAND_SMART = new BlockFallingTrapSandSmart("falling_trap_sand_smart");
	public static final Block PLANKS = new BlockUBSPlanks("planks");
	
}